-- Fitti — initial schema
--
-- Every table is owner-scoped through user_id and RLS. This is photographs of
-- people's clothes and bedrooms: the database refuses to hand a row to anyone
-- but its owner, so a bug in a route handler cannot leak a closet.
--
-- Image BYTES live in Cloudflare R2, never here. Postgres holds object keys and
-- metadata only. See docs/DECISIONS.md for why.

create extension if not exists vector with schema extensions;

-- ---------------------------------------------------------------------------
-- profiles
-- ---------------------------------------------------------------------------
create table if not exists public.profiles (
  id             uuid primary key references auth.users (id) on delete cascade,
  display_name   text,

  -- The screen color. Assigned at signup, later derived from the dominant color
  -- of the clothes they own, always overridable in Appearance.
  ground         text not null default 'butter' check (ground in
                   ('butter','amber','terracotta','rose','blush','orchid',
                    'violet','blue','sky','teal','jade','moss')),
  -- False once the user picks a ground by hand, so the closet-derived color
  -- stops overwriting a deliberate choice.
  ground_is_auto boolean not null default true,

  -- Sizes drive the single biggest hard filter in Discover.
  sizes          jsonb not null default '{}',

  -- Per-user inbound address for receipt forwarding: u_<slug>@in.fitti.app.
  -- Random, not derived from the user id, so knowing one address tells you
  -- nothing about anyone else's.
  inbox_slug     text unique,

  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- garments
--
-- Deliberately narrow: this is the table the closet grid scans, and every extra
-- byte per row is fewer rows per 8KB page. Embeddings and per-variant asset
-- rows live in their own tables for exactly that reason.
-- ---------------------------------------------------------------------------
create table if not exists public.garments (
  -- Generated by the CLIENT before the first byte moves, so a retried upload is
  -- idempotent for free (ON CONFLICT DO NOTHING) and the device can render an
  -- optimistic card that already has its final identity.
  id            uuid primary key,
  user_id       uuid not null default auth.uid() references auth.users (id) on delete cascade,

  name          text,
  category      text check (category in
                  ('top','bottom','dress','outerwear','footwear','accessory')),
  subcategory   text,

  -- Which outfit slots this garment occupies. A dress is {top,bottom} — it is
  -- one garment filling two slots, which the old fits Category/Slot split could
  -- not express and the outfit engine needs to get right.
  covers        text[] not null default '{}',

  -- Colors are computed, never named by a language model: k-means on the masked
  -- pixels, converted to CIELAB, matched to the nearest ISCC-NBS name by
  -- deltaE2000. A VLM says "navy" and "midnight" for the same jacket on two runs.
  color_name    text,
  color_hex     text,
  color_palette jsonb not null default '[]',

  pattern       text,
  material      text,
  fit           text,
  brand         text,
  formality     smallint check (formality between 1 and 5),
  seasons       text[] not null default '{}',

  -- Per-field confidence from the tagging pass. Anything below ~0.6 is hidden
  -- rather than shown wrong: vision models are weakest at knowing when an
  -- attribute does not apply at all.
  attrs         jsonb not null default '{}',
  confidence    jsonb not null default '{}',

  times_worn    integer not null default 0,
  last_worn_on  date,
  favorite      boolean not null default false,

  source        text not null default 'camera' check (source in
                  ('camera','library','share_ext','email','web')),
  source_url    text,

  -- pending -> uploading -> processing -> ready, or failed/quarantined.
  -- Anything not 'ready' is never served.
  status        text not null default 'pending' check (status in
                  ('pending','uploading','processing','ready','failed','quarantined')),
  failure_reason text,

  -- Denormalized render pointers so the grid never joins.
  thumb_key     text,
  cutout_key    text,
  master_key    text,
  -- ThumbHash, ~23 bytes. Not BlurHash: BlurHash cannot encode alpha, and every
  -- image here is a transparent cutout, so a BlurHash of one is a smear of the
  -- matte color that looks nothing like the tile it stands in for.
  thumbhash     bytea,
  width         integer,
  height        integer,

  -- Reserved for the social layer. Nothing reads it yet; it exists so that
  -- shipping social later is an additive migration rather than a rewrite.
  visibility    text not null default 'private' check (visibility in ('private','friends','public')),

  deleted_at    timestamptz,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

-- The grid query, and the RLS predicate. Keyset pagination rides this directly.
create index if not exists garments_user_created_idx
  on public.garments (user_id, created_at desc, id desc) where deleted_at is null;

create index if not exists garments_user_category_idx
  on public.garments (user_id, category) where deleted_at is null;

-- Outfit assembly filters on which slots a garment can fill.
create index if not exists garments_covers_idx on public.garments using gin (covers);
create index if not exists garments_attrs_idx on public.garments using gin (attrs jsonb_path_ops);

-- Drives the ingest worker's "what still needs work" sweep.
create index if not exists garments_pending_idx on public.garments (status)
  where status in ('pending','uploading','processing');

-- ---------------------------------------------------------------------------
-- garment_assets — one row per derivative rung, the record of what exists in R2
-- ---------------------------------------------------------------------------
create table if not exists public.garment_assets (
  id           uuid primary key default gen_random_uuid(),
  garment_id   uuid not null references public.garments (id) on delete cascade,
  -- Denormalized so the RLS policy needs no join. Policies that join are a
  -- well-known performance cliff.
  user_id      uuid not null default auth.uid() references auth.users (id) on delete cascade,

  role         text not null check (role in ('original','master','cutout','preview','thumb')),
  object_key   text not null,
  content_type text not null,
  bytes        bigint not null,
  width        integer not null,
  height       integer not null,
  has_alpha    boolean not null default false,
  -- sha256, for dedupe and for making a retried derive idempotent.
  checksum     text,
  storage_class text not null default 'standard' check (storage_class in ('standard','infrequent')),

  created_at   timestamptz not null default now(),
  unique (garment_id, role)
);

create unique index if not exists garment_assets_key_idx on public.garment_assets (object_key);
create index if not exists garment_assets_garment_idx on public.garment_assets (garment_id);

-- ---------------------------------------------------------------------------
-- garment_embeddings — separate table on purpose
--
-- A 512-dim halfvec is ~1KB. Inline on garments it would push rows past the
-- TOAST threshold, so the grid query would pay detoast cost on data it never
-- reads. The model column also lets two embedding generations coexist during a
-- re-embed rather than requiring a flag day.
-- ---------------------------------------------------------------------------
create table if not exists public.garment_embeddings (
  garment_id uuid primary key references public.garments (id) on delete cascade,
  user_id    uuid not null default auth.uid() references auth.users (id) on delete cascade,
  model      text not null default 'marqo-fashionSigLIP',
  -- halfvec (float16) halves storage at under 1% recall cost on normalized vectors.
  embedding  extensions.halfvec(512) not null,
  created_at timestamptz not null default now()
);

create index if not exists garment_embeddings_hnsw_idx
  on public.garment_embeddings using hnsw (embedding extensions.halfvec_cosine_ops);

-- ---------------------------------------------------------------------------
-- outfits
-- ---------------------------------------------------------------------------
create table if not exists public.outfits (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null default auth.uid() references auth.users (id) on delete cascade,

  name       text,
  -- One sentence of why, from the stylist pass. This is what makes the feature
  -- read as styling rather than as shuffling.
  rationale  text,
  note       text,
  occasion   text,
  visibility text not null default 'private' check (visibility in ('private','friends','public')),

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists outfits_user_created_idx
  on public.outfits (user_id, created_at desc);

create table if not exists public.outfit_items (
  outfit_id  uuid not null references public.outfits (id) on delete cascade,
  garment_id uuid not null references public.garments (id) on delete cascade,
  -- Which slot this garment fills in THIS outfit. A dress covers {top,bottom},
  -- so it appears once per slot it is filling.
  slot       text not null check (slot in ('top','bottom','outerwear','footwear','accessory')),
  primary key (outfit_id, garment_id, slot)
);

-- ---------------------------------------------------------------------------
-- wears — what was actually worn, which is the only honest signal of taste
-- ---------------------------------------------------------------------------
create table if not exists public.wears (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null default auth.uid() references auth.users (id) on delete cascade,
  outfit_id  uuid references public.outfits (id) on delete set null,
  garment_id uuid references public.garments (id) on delete cascade,
  worn_on    date not null default current_date,
  created_at timestamptz not null default now()
);

create index if not exists wears_user_date_idx on public.wears (user_id, worn_on desc);

-- ---------------------------------------------------------------------------
-- style_context — free-form taste input: pasted links, notes, saved images
-- ---------------------------------------------------------------------------
create table if not exists public.style_context (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null default auth.uid() references auth.users (id) on delete cascade,
  kind       text not null check (kind in ('text','link','image')),
  content    text not null check (char_length(content) <= 4000),
  tags       text[] not null default '{}',
  created_at timestamptz not null default now()
);

create index if not exists style_context_user_created_idx
  on public.style_context (user_id, created_at desc);

-- ---------------------------------------------------------------------------
-- catalog_items — the Discover inventory. NOT user data: world-readable.
--
-- Seeded for v1, then affiliate feeds. affiliate_url is not optional: stripping
-- it would breach the feed licence that permits showing the image at all.
-- ---------------------------------------------------------------------------
create table if not exists public.catalog_items (
  id            uuid primary key default gen_random_uuid(),
  source        text not null,
  external_id   text not null,

  title         text not null,
  brand         text,
  category      text,
  covers        text[] not null default '{}',
  color_name    text,
  color_hex     text,
  pattern       text,
  material      text,
  price_cents   integer,
  currency      text not null default 'USD',
  sizes         text[] not null default '{}',

  -- Garment-only image. The feed shows this and nothing else.
  cutout_url    text,
  -- Someone wearing it, revealed on press-and-hold. Often null.
  worn_url      text,
  affiliate_url text not null,

  -- A VLM caption written at ingest, embedded alongside the title. Retailer
  -- titles are SEO sludge ("Women's Top NEW SS26 BLK"); the caption is what
  -- makes text search work at all.
  caption       text,

  in_stock      boolean not null default true,
  listed_at     timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  unique (source, external_id)
);

create index if not exists catalog_live_idx
  on public.catalog_items (category, listed_at desc) where in_stock;
create index if not exists catalog_sizes_idx on public.catalog_items using gin (sizes);

create table if not exists public.catalog_embeddings (
  catalog_item_id uuid primary key references public.catalog_items (id) on delete cascade,
  model           text not null default 'marqo-fashionSigLIP',
  embedding       extensions.halfvec(512) not null,
  created_at      timestamptz not null default now()
);

create index if not exists catalog_embeddings_hnsw_idx
  on public.catalog_embeddings using hnsw (embedding extensions.halfvec_cosine_ops);

-- ---------------------------------------------------------------------------
-- feed_requests + events — the recommendation training log
--
-- request_id and position are the two fields that can never be backfilled.
-- Without request_id an impression cannot be tied to the ranked list that
-- produced it; without position every offline metric is position-biased and
-- therefore wrong. Log them from the first day or the data is worthless.
-- ---------------------------------------------------------------------------
create table if not exists public.feed_requests (
  id             uuid primary key default gen_random_uuid(),
  user_id        uuid not null default auth.uid() references auth.users (id) on delete cascade,
  session_id     uuid not null,
  surface        text not null,
  ranker_version text not null,
  epsilon        real,
  candidate_count integer,
  returned_items uuid[] not null default '{}',
  -- Which centroids were used and how much signal existed, so a bad feed can be
  -- reconstructed months later instead of guessed at.
  profile_snapshot jsonb not null default '{}',
  latency_ms     integer,
  created_at     timestamptz not null default now()
);

create index if not exists feed_requests_user_idx on public.feed_requests (user_id, created_at desc);

create table if not exists public.events (
  id              bigserial primary key,
  user_id         uuid not null default auth.uid() references auth.users (id) on delete cascade,
  session_id      uuid not null,
  request_id      uuid references public.feed_requests (id) on delete set null,

  event_type      text not null check (event_type in
                    ('impression','viewport_exit','peek','tap_through','detail_exit',
                     'image_swipe','zoom','like','save','unsave','add_to_closet',
                     'outfit_include','share','click_out','purchase','dismiss',
                     'hide_brand','search','filter_apply','feed_refresh')),
  catalog_item_id uuid references public.catalog_items (id) on delete set null,
  garment_id      uuid references public.garments (id) on delete set null,

  surface         text not null,
  position        integer,
  page            integer,
  pool            text,
  is_explore      boolean not null default false,

  -- The highest-value implicit signal in the whole system, and the one everyone
  -- forgets to instrument.
  dwell_ms        integer,
  visible_pct     smallint,

  ranker_version    text,
  score             real,
  score_breakdown   jsonb,
  embedding_version text,

  query           text,
  filters         jsonb,
  client          jsonb,
  created_at      timestamptz not null default now()
);

create index if not exists events_user_time_idx on public.events (user_id, created_at desc);
create index if not exists events_request_idx on public.events (request_id);
create index if not exists events_positive_idx on public.events (user_id, created_at desc)
  where event_type in ('like','save','add_to_closet','outfit_include','click_out','purchase');

-- ---------------------------------------------------------------------------
-- entitlements — 25 garments free, then subscription
--
-- Enforced here, server-side, against a StoreKit-verified row. Never trust the
-- client's word for what it has paid for.
-- ---------------------------------------------------------------------------
create table if not exists public.entitlements (
  user_id            uuid primary key references auth.users (id) on delete cascade,
  tier               text not null default 'free' check (tier in ('free','plus')),
  garment_limit      integer not null default 25,
  original_txn_id    text unique,
  expires_at         timestamptz,
  updated_at         timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- ai_usage — a rate limiter caps request RATE. This caps monthly SPEND.
-- ---------------------------------------------------------------------------
create table if not exists public.ai_usage (
  user_id    uuid not null default auth.uid() references auth.users (id) on delete cascade,
  day        date not null default current_date,
  calls      integer not null default 0,
  cost_cents integer not null default 0,
  primary key (user_id, day)
);

-- ---------------------------------------------------------------------------
-- ingest_jobs — server mirror of the device queue; the support/DLQ view
-- ---------------------------------------------------------------------------
create table if not exists public.ingest_jobs (
  id              uuid primary key default gen_random_uuid(),
  garment_id      uuid not null references public.garments (id) on delete cascade,
  user_id         uuid not null default auth.uid() references auth.users (id) on delete cascade,
  kind            text not null check (kind in
                    ('derive','moderate','cutout','tag','embed','email_parse','bulk_split')),
  state           text not null default 'queued' check (state in
                    ('queued','running','done','failed','dead')),
  attempts        integer not null default 0,
  next_attempt_at timestamptz not null default now(),
  last_error      text,
  created_at      timestamptz not null default now()
);

-- Partial index so the worker's claim query touches only claimable rows.
create index if not exists ingest_jobs_claimable_idx
  on public.ingest_jobs (next_attempt_at) where state in ('queued','failed');

-- ---------------------------------------------------------------------------
-- updated_at
-- ---------------------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at before update on public.profiles
  for each row execute function public.set_updated_at();

drop trigger if exists garments_set_updated_at on public.garments;
create trigger garments_set_updated_at before update on public.garments
  for each row execute function public.set_updated_at();

drop trigger if exists outfits_set_updated_at on public.outfits;
create trigger outfits_set_updated_at before update on public.outfits
  for each row execute function public.set_updated_at();

-- Give every new user a profile and a free-tier entitlement. Doing this in a
-- trigger rather than in app code means there is no window where a signed-up
-- user has no row, whatever path they signed up through.
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  insert into public.profiles (id, ground, inbox_slug)
  values (
    new.id,
    -- Assigned, not chosen. Becomes the dominant closet color once there are
    -- enough garments to have one.
    (array['butter','amber','terracotta','rose','blush','orchid',
           'violet','blue','sky','teal','jade','moss'])[floor(random() * 12 + 1)],
    encode(extensions.gen_random_bytes(6), 'hex')
  )
  on conflict (id) do nothing;

  insert into public.entitlements (user_id) values (new.id)
  on conflict (user_id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();
